"""Refactor models and fix UUID types

Revision ID: bbd11880a237
Revises: bbe35dd80566
Create Date: 2025-12-29 20:01:26.824455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd11880a237'
down_revision: Union[str, Sequence[str], None] = 'bbe35dd80566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rooms_invite_code_key'), 'rooms', type_='unique')
    op.create_unique_constraint(op.f('uq_rooms_invite_code'), 'rooms', ['invite_code'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_rooms_invite_code'), 'rooms', type_='unique')
    op.create_unique_constraint(op.f('rooms_invite_code_key'), 'rooms', ['invite_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
