"""Update FocusSession

Revision ID: bbe35dd80566
Revises: fca591d11595
Create Date: 2025-12-29 14:03:16.132888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe35dd80566'
down_revision: Union[str, Sequence[str], None] = 'fca591d11595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_sessions', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('focus_sessions', 'duration_minutes')
    # ### end Alembic commands ###
