"""Update Table

Revision ID: fca591d11595
Revises: 168edb5249e1
Create Date: 2025-12-29 13:45:49.866047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca591d11595'
down_revision: Union[str, Sequence[str], None] = '168edb5249e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_sessions', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('focus_sessions', 'is_active')
    # ### end Alembic commands ###
